### ISSUE TITLE
SecurityError: Insecure operation - file?

### ISSUE THREAD

**Issue by leifcr** [flajann2/juwelier#7]
Same issue as technicalpickles/jeweler#304 for ruby 2.6+

Solution that perhaps can be implemented in juwelier: 
https://github.com/hiptest/jeweler/commit/85f9d8d0ed2d4f9c309b009af1b431d29c1330fb

Works fine to downgrade to 2.5 to release gems just for performing rake release.

**Comment by flajann2** [comment]
Let me take a look at that. Besides, I need to rev all of my Ruby projects for 2.6, anyway.

**Comment by leifcr** [comment]
@flajann2 thanks

**Comment by homonecloco** [comment]
Any updates on this?

**Comment by zanloy** [comment]
Please implement this and release a new version to rubygems.org. It would be nice to use juwelier on ruby >= 2.6

**Comment by weshatheleopard** [comment]
Bumping to ruby 2.7.4 solved the problem.
